# Usage: conda env create -n myenvname -f environment.yml
---
name: aiida
channels:
- conda-forge
- defaults
dependencies:
- python>=3.7,<4
- aldjemy>=0.9.1,<0.10
- alembic>=1.2,<2
- aio-pika>=6.6,<7
- circus>=0.16.1,<0.17
- click-completion>=0.5.1,<0.6
- click-config-file>=0.6.0,<0.7
- click-spinner>=0.1.8,<0.2
- click>=7.0,<8
- django>=2.2,<3
- ete3>=3.1,<4
- python-graphviz>=0.13,<0.14
- ipython>=7.0,<8
- jinja2>=2.10,<3
- kiwipy[rmq]>=0.6.1,<0.7
- numpy<1.18,>=1.17
- paramiko>=2.7,<3
- plumpy>=0.16.1,<0.17
- pgsu>=0.1.0,<0.2
- psutil>=5.6,<6
- psycopg2>=2.8.3,<2.9
- python-dateutil>=2.8,<3
- pytz>=2019.3
- pyyaml==5.1.2
- reentry>=1.3,<2
- simplejson>=3.16,<4
- sqlalchemy-utils>=0.34.2,<0.35
- sqlalchemy>=1.3.10,<2
- tabulate>=0.8.5,<0.9
- tqdm>=4.45,<5
- tzlocal>=2.0,<3
- upf_to_json>=0.9.2,<0.10
- wrapt>=1.11.1,<2
