name: test-install

on:
  push:
    paths:
      - 'environment.yml'
      - '**/requirements*.txt'
      - 'pyproject.toml'
      - 'util/dependency_management.py'
      - '.github/workflows/test-install.yml'
      - '.github/workflows/ci-code.yml'
    branches-ignore: [gh-pages]
  pull_request:
    paths:
      - 'environment.yml'
      - '**/requirements*.txt'
      - 'pyproject.toml'
      - 'util/dependency_management.py'
      - '.github/workflows/test-install.yml'
    branches-ignore: [gh-pages]
  schedule:
    - cron: '30 02 * * *'  # nightly build

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  # if: github.repository == 'aiidateam/aiida-core'


  test-install:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    uses: ./.github/workflows/test-install.yml
    with:
      python-version: ${{ matrix.python-version }}
  
