name: docs-build

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]
    paths: ['docs/**']

jobs:

  docs-linkcheck:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python dependencies
      run: |
        pip install -e .[docs,tests]
    - name: "Build HTML docs"
      run: |
        make -C docs html linkcheck
      env:
        SPHINXOPTS: -nW --keep-going
